# Generated by Django 4.2.28 on 2026-02-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
