from django.urls import path
from . import views

app_name = 'engagement'

urlpatterns = [
    # === Engagement Surveys ===
    path('surveys/', views.SurveyListView.as_view(), name='survey_list'),
    path('surveys/create/', views.SurveyCreateView.as_view(), name='survey_create'),
    path('surveys/<int:pk>/', views.SurveyDetailView.as_view(), name='survey_detail'),
    path('surveys/<int:pk>/edit/', views.SurveyUpdateView.as_view(), name='survey_edit'),
    path('surveys/<int:pk>/delete/', views.SurveyDeleteView.as_view(), name='survey_delete'),
    path('surveys/<int:pk>/questions/create/', views.SurveyQuestionCreateView.as_view(), name='survey_question_create'),
    path('surveys/questions/<int:pk>/edit/', views.SurveyQuestionUpdateView.as_view(), name='survey_question_edit'),
    path('surveys/questions/<int:pk>/delete/', views.SurveyQuestionDeleteView.as_view(), name='survey_question_delete'),
    path('surveys/questions/<int:pk>/options/create/', views.SurveyQuestionOptionCreateView.as_view(), name='survey_question_option_create'),
    path('surveys/options/<int:pk>/delete/', views.SurveyQuestionOptionDeleteView.as_view(), name='survey_question_option_delete'),
    path('surveys/<int:pk>/respond/', views.SurveyRespondView.as_view(), name='survey_respond'),
    path('surveys/responses/<int:pk>/', views.SurveyResponseDetailView.as_view(), name='survey_response_detail'),
    path('action-plans/', views.SurveyActionPlanListView.as_view(), name='action_plan_list'),
    path('surveys/<int:pk>/action-plans/create/', views.SurveyActionPlanCreateView.as_view(), name='action_plan_create'),
    path('action-plans/<int:pk>/edit/', views.SurveyActionPlanUpdateView.as_view(), name='action_plan_edit'),
    path('action-plans/<int:pk>/delete/', views.SurveyActionPlanDeleteView.as_view(), name='action_plan_delete'),

    # === Wellbeing Programs ===
    path('programs/', views.WellbeingProgramListView.as_view(), name='program_list'),
    path('programs/create/', views.WellbeingProgramCreateView.as_view(), name='program_create'),
    path('programs/<int:pk>/', views.WellbeingProgramDetailView.as_view(), name='program_detail'),
    path('programs/<int:pk>/edit/', views.WellbeingProgramUpdateView.as_view(), name='program_edit'),
    path('programs/<int:pk>/delete/', views.WellbeingProgramDeleteView.as_view(), name='program_delete'),
    path('resources/', views.WellbeingResourceListView.as_view(), name='resource_list'),
    path('resources/create/', views.WellbeingResourceCreateView.as_view(), name='resource_create'),
    path('resources/<int:pk>/', views.WellbeingResourceDetailView.as_view(), name='resource_detail'),
    path('resources/<int:pk>/edit/', views.WellbeingResourceUpdateView.as_view(), name='resource_edit'),
    path('resources/<int:pk>/delete/', views.WellbeingResourceDeleteView.as_view(), name='resource_delete'),
    path('challenges/', views.WellnessChallengeListView.as_view(), name='challenge_list'),
    path('challenges/create/', views.WellnessChallengeCreateView.as_view(), name='challenge_create'),
    path('challenges/<int:pk>/', views.WellnessChallengeDetailView.as_view(), name='challenge_detail'),
    path('challenges/<int:pk>/edit/', views.WellnessChallengeUpdateView.as_view(), name='challenge_edit'),
    path('challenges/<int:pk>/delete/', views.WellnessChallengeDeleteView.as_view(), name='challenge_delete'),
    path('challenges/<int:pk>/participate/', views.ChallengeParticipantCreateView.as_view(), name='challenge_participate'),
    path('challenges/participants/<int:pk>/edit/', views.ChallengeParticipantUpdateView.as_view(), name='challenge_participant_edit'),

    # === Work-Life Balance ===
    path('arrangements/', views.FlexibleWorkArrangementListView.as_view(), name='arrangement_list'),
    path('arrangements/create/', views.FlexibleWorkArrangementCreateView.as_view(), name='arrangement_create'),
    path('arrangements/<int:pk>/', views.FlexibleWorkArrangementDetailView.as_view(), name='arrangement_detail'),
    path('arrangements/<int:pk>/edit/', views.FlexibleWorkArrangementUpdateView.as_view(), name='arrangement_edit'),
    path('arrangements/<int:pk>/delete/', views.FlexibleWorkArrangementDeleteView.as_view(), name='arrangement_delete'),
    path('remote-policies/', views.RemoteWorkPolicyListView.as_view(), name='remote_policy_list'),
    path('remote-policies/create/', views.RemoteWorkPolicyCreateView.as_view(), name='remote_policy_create'),
    path('remote-policies/<int:pk>/', views.RemoteWorkPolicyDetailView.as_view(), name='remote_policy_detail'),
    path('remote-policies/<int:pk>/edit/', views.RemoteWorkPolicyUpdateView.as_view(), name='remote_policy_edit'),
    path('remote-policies/<int:pk>/delete/', views.RemoteWorkPolicyDeleteView.as_view(), name='remote_policy_delete'),
    path('wlb-assessments/', views.WorkLifeBalanceAssessmentListView.as_view(), name='wlb_assessment_list'),
    path('wlb-assessments/create/', views.WorkLifeBalanceAssessmentCreateView.as_view(), name='wlb_assessment_create'),
    path('wlb-assessments/<int:pk>/', views.WorkLifeBalanceAssessmentDetailView.as_view(), name='wlb_assessment_detail'),
    path('wlb-assessments/<int:pk>/edit/', views.WorkLifeBalanceAssessmentUpdateView.as_view(), name='wlb_assessment_edit'),
    path('wlb-assessments/<int:pk>/delete/', views.WorkLifeBalanceAssessmentDeleteView.as_view(), name='wlb_assessment_delete'),

    # === Employee Assistance ===
    path('eap-programs/', views.EAPProgramListView.as_view(), name='eap_program_list'),
    path('eap-programs/create/', views.EAPProgramCreateView.as_view(), name='eap_program_create'),
    path('eap-programs/<int:pk>/', views.EAPProgramDetailView.as_view(), name='eap_program_detail'),
    path('eap-programs/<int:pk>/edit/', views.EAPProgramUpdateView.as_view(), name='eap_program_edit'),
    path('eap-programs/<int:pk>/delete/', views.EAPProgramDeleteView.as_view(), name='eap_program_delete'),
    path('counseling/', views.CounselingSessionListView.as_view(), name='counseling_list'),
    path('counseling/create/', views.CounselingSessionCreateView.as_view(), name='counseling_create'),
    path('counseling/<int:pk>/', views.CounselingSessionDetailView.as_view(), name='counseling_detail'),
    path('counseling/<int:pk>/edit/', views.CounselingSessionUpdateView.as_view(), name='counseling_edit'),
    path('counseling/<int:pk>/delete/', views.CounselingSessionDeleteView.as_view(), name='counseling_delete'),
    path('eap-programs/<int:pk>/utilization/create/', views.EAPUtilizationCreateView.as_view(), name='eap_utilization_create'),
    path('eap-utilization/<int:pk>/edit/', views.EAPUtilizationUpdateView.as_view(), name='eap_utilization_edit'),
    path('eap-utilization/<int:pk>/delete/', views.EAPUtilizationDeleteView.as_view(), name='eap_utilization_delete'),

    # === Culture & Values ===
    path('values/', views.CompanyValueListView.as_view(), name='value_list'),
    path('values/create/', views.CompanyValueCreateView.as_view(), name='value_create'),
    path('values/<int:pk>/', views.CompanyValueDetailView.as_view(), name='value_detail'),
    path('values/<int:pk>/edit/', views.CompanyValueUpdateView.as_view(), name='value_edit'),
    path('values/<int:pk>/delete/', views.CompanyValueDeleteView.as_view(), name='value_delete'),
    path('culture-assessments/', views.CultureAssessmentListView.as_view(), name='culture_assessment_list'),
    path('culture-assessments/create/', views.CultureAssessmentCreateView.as_view(), name='culture_assessment_create'),
    path('culture-assessments/<int:pk>/', views.CultureAssessmentDetailView.as_view(), name='culture_assessment_detail'),
    path('culture-assessments/<int:pk>/edit/', views.CultureAssessmentUpdateView.as_view(), name='culture_assessment_edit'),
    path('culture-assessments/<int:pk>/delete/', views.CultureAssessmentDeleteView.as_view(), name='culture_assessment_delete'),
    path('culture-assessments/<int:pk>/respond/', views.CultureAssessmentRespondView.as_view(), name='culture_assessment_respond'),
    path('nominations/', views.ValueNominationListView.as_view(), name='nomination_list'),
    path('nominations/create/', views.ValueNominationCreateView.as_view(), name='nomination_create'),
    path('nominations/<int:pk>/edit/', views.ValueNominationUpdateView.as_view(), name='nomination_edit'),
    path('nominations/<int:pk>/delete/', views.ValueNominationDeleteView.as_view(), name='nomination_delete'),

    # === Social Connect ===
    path('events/', views.TeamEventListView.as_view(), name='event_list'),
    path('events/create/', views.TeamEventCreateView.as_view(), name='event_create'),
    path('events/<int:pk>/', views.TeamEventDetailView.as_view(), name='event_detail'),
    path('events/<int:pk>/edit/', views.TeamEventUpdateView.as_view(), name='event_edit'),
    path('events/<int:pk>/delete/', views.TeamEventDeleteView.as_view(), name='event_delete'),
    path('events/<int:pk>/participate/', views.EventParticipantCreateView.as_view(), name='event_participate'),
    path('events/participants/<int:pk>/edit/', views.EventParticipantUpdateView.as_view(), name='event_participant_edit'),
    path('interest-groups/', views.InterestGroupListView.as_view(), name='interest_group_list'),
    path('interest-groups/create/', views.InterestGroupCreateView.as_view(), name='interest_group_create'),
    path('interest-groups/<int:pk>/', views.InterestGroupDetailView.as_view(), name='interest_group_detail'),
    path('interest-groups/<int:pk>/edit/', views.InterestGroupUpdateView.as_view(), name='interest_group_edit'),
    path('interest-groups/<int:pk>/delete/', views.InterestGroupDeleteView.as_view(), name='interest_group_delete'),
    path('interest-groups/<int:pk>/join/', views.InterestGroupMemberCreateView.as_view(), name='interest_group_join'),
    path('interest-groups/members/<int:pk>/remove/', views.InterestGroupMemberDeleteView.as_view(), name='interest_group_member_remove'),
    path('volunteering/', views.VolunteerActivityListView.as_view(), name='volunteer_list'),
    path('volunteering/create/', views.VolunteerActivityCreateView.as_view(), name='volunteer_create'),
    path('volunteering/<int:pk>/', views.VolunteerActivityDetailView.as_view(), name='volunteer_detail'),
    path('volunteering/<int:pk>/edit/', views.VolunteerActivityUpdateView.as_view(), name='volunteer_edit'),
    path('volunteering/<int:pk>/delete/', views.VolunteerActivityDeleteView.as_view(), name='volunteer_delete'),
    path('volunteering/<int:pk>/participate/', views.VolunteerParticipantCreateView.as_view(), name='volunteer_participate'),
    path('volunteering/participants/<int:pk>/edit/', views.VolunteerParticipantUpdateView.as_view(), name='volunteer_participant_edit'),
]
