# Generated by Django 4.2.28 on 2026-03-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0002_alter_costcenter_code'),
        ('employees', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scenario_type', models.CharField(choices=[('growth', 'Growth'), ('restructuring', 'Restructuring'), ('downsizing', 'Downsizing'), ('merger', 'Merger'), ('expansion', 'Expansion')], default='growth', max_length=15)),
                ('base_year', models.CharField(max_length=20)),
                ('projection_year', models.CharField(max_length=20)),
                ('assumptions', models.TextField(blank=True)),
                ('impact_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('gap_type', models.CharField(choices=[('surplus', 'Surplus'), ('deficit', 'Deficit'), ('balanced', 'Balanced')], default='balanced', max_length=10)),
                ('skills_gap_description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('action_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('deferred', 'Deferred')], default='identified', max_length=15)),
                ('fiscal_year', models.CharField(blank=True, max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_gaps', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_gaps', to='organization.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilizationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('productive_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('non_billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilization_rates', to='organization.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilization_rates', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('on_notice_count', models.PositiveIntegerField(default=0)),
                ('retiring_count', models.PositiveIntegerField(default=0)),
                ('transfer_ready_count', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_availability', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_availability', to='organization.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Talent Availabilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_headcount', models.PositiveIntegerField(default=0)),
                ('projected_headcount', models.PositiveIntegerField(default=0)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_details', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_details', to='organization.designation')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workforce.workforcescenario')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['department', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='SalaryForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_avg_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('projected_avg_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('increment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_forecasts', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_forecasts', to='organization.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('measurement_period', models.CharField(max_length=20)),
                ('measurement_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_metrics', to='organization.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_metrics', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='HiringBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('utilized_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('positions_budgeted', models.PositiveIntegerField(default=0)),
                ('positions_filled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_budgets', to='organization.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('current_headcount', models.PositiveIntegerField(default=0)),
                ('projected_headcount', models.PositiveIntegerField(default=0)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to='organization.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=255)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('certified', models.BooleanField(default=False)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_inventories', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Skill Inventories',
                'ordering': ['employee', 'skill_name'],
                'unique_together': {('employee', 'skill_name', 'tenant')},
            },
        ),
    ]
